### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by dpryan79** [Biobix/DeepRibo#6]
Can you tag a release on github? That would allow people to version control their installations better and allow easier redistribution by Bioconda.

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/19983

**Comment by jdcla** [comment]
This should be resolved. I have updated the repository to work with python 3.8 and PyTorch 1.4.
Thank you for the reference.

**Comment by priyansha016** [comment]
I have strand specififc riboseq bam files. How to convert into 4 bedgraph files?
