### ISSUE TITLE
How to convert fastQ file into four Bedgraph files

### ISSUE THREAD

**Issue by Merofine** [Biobix/DeepRibo#8]
hi guy, Do you have a manual or something that explains the conversion process?
Thanks a lot ~

**Comment by Merofine** [comment]
In short, the ribosome profiling data of elongating ribosomes has to be compiled into four bedgraph files. These contain the coverage signals of all reads and the mapped A/P profiles (reads mapped to one site). The following steps are performed:
read adapters are trimmed
rRNA sequences are filtered out and only uniquely mapped reads are used
a 12nt offset from the 3' end of the read is used to map reads to a single position on the genome.

I have a fastq file(the ribosome profiling data of elongating ribosomes), and I want to get  four bedgraph files like u.This is making me dizzy.~Thank you  very very much ~

**Comment by Merofine** [comment]
This is very helpful to the progress of our project. I'm also glad to see such a good model(DeepRibo)

**Comment by priyansha016** [comment]
Hi @Merofine , Did you find how to do it?  I have strand specific bam files. How to convert into 4 bedgraph files?

**Comment by jdcla** [comment]
There are multiple tools online to achieve this, simply google your question for discussions on this (e.g. https://www.biostars.org/p/312239/).

Additionally, after doing this, you can check the files used for the study to see whether your files look in order. see http://www.biobix.be/deepribo/

**Comment by priyansha016** [comment]
I know the commands to convert into bedgraph file. I don't understand how to specifically look for elongating coverage and A-sites.

**Comment by jdcla** [comment]
I cannot look into the exact commands I used for pre-processing the files, but know these conversions can be achieved with samtools or bedtools.

If you delve into the functionality of these tools you should be able to find the necessary commands.

**Comment by Merofine** [comment]
thanks a lot.



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 27, 2023 20:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Biobix/DeepRibo] How to convert fastQ file into four Bedgraphfiles (#8)




 
I cannot look into the exact commands I used for pre-processing the files, but know these conversions can be achieved with samtools or bedtools.
 
If you delve into the functionality of these tools you should be able to find the necessary commands.

**Comment by priyansha016** [comment]
I will look into it. Thanks!

**Comment by jdcla** [comment]
I did a quick search and found this: https://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html

Using the `-3` argument allows you to map reads to a single positions, you can shift the reads with 12 nt afterwards.
I'll edit the README.md to include this info.

edit: ~~`-5`~~ -> `-3`

**Comment by priyansha016** [comment]
I have a doubt in the 'Data preparation' section. It says 12nt offset from 3' end of the read. But SD would be on 5' end. Or am I getting it wrong?

**Comment by jdcla** [comment]
You are correct. I corrected my mistake.
Thanks for verifying.
